services:
  superset:
    build: ./superset
    container_name: superset
    environment:
      ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset_config.py:/app/superset_config.py
      - ./superset/superset-init.sh:/app/superset-init.sh