services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres

  dashboard:
    extends:
      file: ./services/dashboard/docker-compose.yml
      service: dashboard

  airflow:
    extends:
      file: ./services/airflow/docker-compose.yml
      service: airflow

  airflow_scheduler:
    extends:
      file: ./services/airflow/docker-compose.yml
      service: airflow_scheduler

networks:
  databox_network:
    driver: bridge

volumes:  
  postgres_data:
  grafana_data:
  pg_admin_data:
  airflow_dags:
  airflow_logs:
  airflow_plugins:
  superset_data:  