version: '3.8'

services:
  db:
    extends:
      file: ./services/db/docker-compose.yml
      service: db

  app:
    extends:
      file: ./services/app/docker-compose.yml
      service: app

  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yml
      service: pgadmin

  grafana:
    extends:
      file: ./services/grafana/docker-compose.yml
      service: grafana

  superset:
    extends:
      file: ./services/superset/docker-compose.yml
      service: superset

networks:
  databox_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

