services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres

  gradio_sql:
    extends:
      file: ./services/gradio_sql/docker-compose.yml
      service: gradio_sql

  dashboard:
    extends:
      file: ./services/dashboard/docker-compose.yml
      service: dashboard

networks:
  databox_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

