services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres

  gradio_sql:
    extends:
      file: ./services/gradio_sql/docker-compose.yml
      service: gradio_sql
      

  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yml
      service: pgadmin

  grafana:
    extends:
      file: ./services/grafana/docker-compose.yml
      service: grafana

  dashboard:
    extends:
      file: ./services/dashboard/docker-compose.yml
      service: dashboard

  airflow:
    extends:
      file: ./services/airflow/docker-compose.yml
      service: airflow


  superset:
    extends:
      file: ./services/superset/docker-compose.yml
      service: superset

networks:
  databox_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

