services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres

  pgadmin:
    extends:
      file: ./services/pgadmin/docker-compose.yml
      service: pgadmin

  grafana:
    extends:
      file: ./services/grafana/docker-compose.yml
      service: grafana

networks:
  databox_network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data:

