version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432" # Exposition du port 5432
    environment:
      POSTGRES_USER: mon_utilisateur
      POSTGRES_PASSWORD: mon_mot_de_passe
      POSTGRES_DB: ma_base_de_donnees
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
