services:
  databox_db_srv:
    build: ./db
    container_name: databox_db
 #   environment:
 #     POSTGRES_USER: admin
 #     POSTGRES_PASSWORD: password
 #     POSTGRES_DB: databox_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: databox_app
    environment:
      DATABASE_URL: postgres://admin:password@db:5432/databox_db
    ports:
      - "7860:7860"
    depends_on:
      - databox_db_srv

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_app
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - databox_db_srv

  grafana:
    image: grafana/grafana
    container_name: grafana_app
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - databox_db_srv

volumes:
  postgres_data:
  grafana_data: