services:
  db:
    build: ./db
    container_name: postgreSQL_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: databox_app
    environment:
      DATABASE_URL: postgres://postgres:yourpassword@db:5432/mydatabase
    ports:
      - "7860:7860"
    depends_on: 
      - db

volumes:
  postgres_data: