[project]
name = "databox"
version = "0.1.0"
description = "a Python app with Gradio Frontend and PostreSQL database Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.20.0",
    "psycopg2-binary>=2.9.10",
]
