services:
  grafana:
    image: grafana/grafana
    container_name: app_grafana
    ports:
      - "3000:3000"
    volumes:
       - grafana_data:/var/lib/grafana
    depends_on:
      - postgres
    networks:
      - databox_network

  volumes:
    grafana_data:
