services:
  postgres:
    build: .
    container_name: db_databox
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
     #- ./services/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - databox_network