  services:
    airflow:
      image: apache/airflow:2.3.0
      container_name: airflow_webserver
      environment:
        AIRFLOW__CORE__EXECUTOR: LocalExecutor
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
        AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      ports:
        - "8080:8080"
      volumes:
        - airflow_dags:/opt/airflow/dags
      networks:
        - databox_network
      depends_on:
        - postgres
      entrypoint: ["airflow", "webserver"]