services:
  airflow:
    build: .
    container_name: airflow_webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8080:8080"
    volumes:
      - airflow_dags:/opt/airflow/dags
    networks:
      - databox_network
    depends_on:
      - postgres
    entrypoint: ["bash", "-c", "airflow db init && airflow users create --username admin --firstname Admin --lastname User --email admin@example.com --role Admin --password adminpassword && airflow webserver"]

  airflow_scheduler:
    build: .
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    volumes:
      - airflow_dags:/opt/airflow/dags
    networks:
      - databox_network
    depends_on:
      - postgres
    entrypoint: ["airflow", "scheduler"]

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - databox_network

volumes:
  airflow_dags:

networks:
  databox_network:
    driver: bridge
